[features]
seeds = false
skip-lint = false

[programs.localnet]
signal = "HP1DdGPWqm1FthSgG6ugQLEq4JUAWjNJp8WWc858qCxB"
tens = "Tensgwm3DY3UJ8nhF7xnD2Wo65VcnLTXjjoyEvs6Zyk"

[programs.devnet]
signal = "HP1DdGPWqm1FthSgG6ugQLEq4JUAWjNJp8WWc858qCxB"
tens = "Tensgwm3DY3UJ8nhF7xnD2Wo65VcnLTXjjoyEvs6Zyk"

[programs.mainnet]
signal = "HP1DdGPWqm1FthSgG6ugQLEq4JUAWjNJp8WWc858qCxB"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "client/tests/fixtures/provider.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 client/tests/*"

[workspace]
types = "client/sdk/src/idl"
members = [
    "programs/signal",
    "examples/tens"
]

[test]
startup_wait = 60000

[[test.genesis]]
address = "metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s"
program = "client/tests/fixtures/mpl_token_metadata.so"
